//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activnost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activnost()
        {
            this.Meropriatie = new HashSet<Meropriatie>();
        }
    
        public int Id { get; set; }
        public string ime { get; set; }
        public Nullable<int> otcenca { get; set; }
        public string Opisanie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meropriatie> Meropriatie { get; set; }
    }
}
