//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meropriatie()
        {
            this.PolzovateliAndMropriatie = new HashSet<PolzovateliAndMropriatie>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ActivnostId { get; set; }
        public string ime { get; set; }
    
        public virtual Activnost Activnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolzovateliAndMropriatie> PolzovateliAndMropriatie { get; set; }
    }
}
