//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrimerEntities : DbContext
    {
        public PrimerEntities()
            : base("name=PrimerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activnost> Activnost { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Meropriatie> Meropriatie { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<PolzovateliAndMropriatie> PolzovateliAndMropriatie { get; set; }
        public virtual DbSet<Roll> Roll { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
