//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolzovateliAndMropriatie
    {
        public int id { get; set; }
        public Nullable<int> PolzovatelId { get; set; }
        public Nullable<int> MeropriatieId { get; set; }
    
        public virtual Meropriatie Meropriatie { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
    }
}
