//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovateli()
        {
            this.PolzovateliAndMropriatie = new HashSet<PolzovateliAndMropriatie>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public int Gender { get; set; }
        public int Rol { get; set; }
        public string Parol { get; set; }
        public string Login { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual Roll Roll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolzovateliAndMropriatie> PolzovateliAndMropriatie { get; set; }
    }
}
